### ISSUE TITLE
BigText not playing with WordPress

### ISSUE THREAD

**Issue by orac808** [zachleat/BigText#51]
I have managed to get a JS based countdown clock to work with BigText.js locally (although I did have to manually fire a page resize event to get to scale down correctly)

Im trying to add it to a page of a wordpress site. I'm working with MAMP - running WordPress 3.8.3 and http://emilolsson.com/hi-response/ as the theme.

I keep getting " Uncaught TypeError: undefined is not a function "
at the point BigText is called.

jQuery(window).load(function () {
 $('#container').bigtext();
});

This works locally using
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>

Hi Response includes 
jquery-1.10.2.min.js
jquery-2.0.2.min.js

in its JS folder.

if this doesn't help I will upload my working demo. I am about to try a vanilla install of WP and see if I can get it working with that.

Thanks in advance.

**Comment by zachleat** [comment]
This should be working better in 0.1.7. Please retest and also look at the stock demo here: zachleat.github.io/BigText/demo/simpleDemo.html

Also make sure that if you’re using `@font-face` that you’re also using a font loader to call BigText after the fonts have loaded.

Please reopen if you have additional questions!
